- name: Add virtual machine custom attributes
  vmware_guest_custom_attributes:
    hostname: "{{ vmware_host }}"
    username: "{{ vmware_user }}"
    password: "{{ vmware_password }}"
    validate_certs: "{{ vmware_validate }}"
    name: "{{ hostname }}"
    state: present
    attributes:
      - name: MyAttribute
        value: MyValue
  delegate_to: localhost