---
- name: Ensure that '{{ hostname }}' is in '{{ rol }}' section of the inventory file 
  ini_file:
    path: './inventories/{{ omgeving}}/{{ bedrijfsnaam }}.ini'
    section: '{{ rol }}'
    option: 
    value: '{{ hostname}}.{{ domain}}'