- name: Ensure Apache is installed
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ httpd_packages }}"

- name: Install main configuration file
  template:
    src: httpd.conf.j2
    dest: "{{ httpd_config }}"
    owner: root
    group: root
    setype: httpd_config_t
    mode: '0644'
  notify: restart httpd

- name: Install status configuration file
  template:
    src: etc_httpd_conf.d_status.conf.j2
    dest: "{{ httpd_status_config }}"
    owner: root
    group: root
    setype: httpd_config_t
    mode: '0644'
  notify: restart httpd
  when: httpd_status_enable

- name: Ensure Apache is always running
  service:
    name: httpd
    state: started
    enabled: true